### ISSUE TITLE
Future plans?

### ISSUE THREAD

**Issue by MuntashirAkon** [mirfatif/NoorUlHuda#2]
1. What are your future plans for this app i.e. do you have any roadmap or something like that because I'm interested in contributing as I find this to be the only Quran app that holds the FOSS values. If you have, it's better you create separate issues for them so that interested contributors can take a look. After the prayer times app scandal in a Malaysian app, I forbid anybody to download a closed source Quran/prayer times app as most of them collect extensive telemetry which can be sold to third-party. However, the open source apps have very limited capabilities. I've planned to create a Quran and a Hadith app, but since you've already created a nice Quran app, I didn't like to reinvent the wheel and create another (This is a QA issue, so I'm not going to propose any feature here). Hence, I'm largely interested in collaboration rather than only contribution.
2. Do you have plans to publish this on F-Droid?

**Comment by mirfatif** [comment]
1. The main reason behind developing NUH was that there isn't any simple, open source and privacy-friendly app available with a clean interface, without unnecessary stuff. Quran reader is the primary goal of the app. Prayer Time and Supplications (Dua) are kinda add-ons. In my opinion these are the things a practicing Muslim is must using on daily basis. I don't intend to add any bigger features to the app which make it less focused. Like Hadith isn't something everyone is using regularly. And the collection of Ahadith is so big that it makes the app inflated (maybe we can make a separate app for that). So the roadmap in my mind up till now is just to maintain the app, add some minor feature (if the idea comes), and improve the UI etc.
2. Yes. I hope it'll find its place on F-Droid: https://gitlab.com/fdroid/rfp/-/issues/1799

Thanks for the interest. جزاكﷲ 🙂
Do share any ideas if you want to. You can also talk to me privately on Telegram.
