### ISSUE TITLE
A bug in Ayah Breaks

### ISSUE THREAD

**Issue by Jakolineuser** [mirfatif/NoorUlHuda#21]
Once Ayah Breaks is activated I lose the ability to long press Ayat or it gets really buggy and becomes a hit or miss, meaning that I can't press Ayat to bookmark or tag them. Please fix that if possible because these line breaks are useful and needed.

**Comment by mirfatif** [comment]
Yes this is a known bug. But no one reported for almost a year. This will be fixed in upcoming release IA. Until then you can long press on the blank space (which includes the Surah name) below the Ayah text and it'll work.

**Comment by mirfatif** [comment]
Fixed in v1.03
