### ISSUE TITLE
Fastlane changelogs have overlength

### ISSUE THREAD

**Issue by IzzySoft** [mirfatif/NoorUlHuda#23]
Per specification, changelogs are limited to 500 chars. The one for versionCode 102 is more than twice that size (1.057 chars) and hence truncated in the middle. Btw, same issue for permissionmanager with `111.txt` being 581 chars.

**Comment by mirfatif** [comment]
I didn't know about the char limit at that time. We discussed this earlier: https://github.com/mirfatif/PermissionManagerX/issues/1#issuecomment-931630482

**Comment by IzzySoft** [comment]
That's why I brought it to your attention: not as a complaint, but as a (hopefully) helpful hint :smiley: I've set up a cron job here that once a month runs over the entire metadata tree watching out for that. It finds something new on every run…

**Comment by mirfatif** [comment]
Thank you so much. I meant I've been careful since I have known about the limit. Should I fix the old ones too?

**Comment by IzzySoft** [comment]
> Should I fix the old ones too?

Only if you want. Setup with my repo is to pull the changelog for the **corresponding** release only. Until now, the index generated by F-Droid only had the latest on in anyway though that might change with v2 – but as my repo keeps max 3 versions, older ones are pruned automatically when newer once come in.

Thanks for taking care!

**Comment by IzzySoft** [comment]
Just wondering, will there be a new release soon™ – or shall we truncate `102.txt` manually one time to avoid my scanner popping the issue into my face once per month?

**Comment by mirfatif** [comment]
I do have plan to work on NUH. But I can't say when I'll be able to give a new release.

**Comment by IzzySoft** [comment]
OK, then I'll see what I can kick out that seems "less important", so the "more important" things show up. If you prefer to sort that yourself, just give me another ping and I'll overwrite my copy with yours.

**Comment by mirfatif** [comment]
I hope v1.03 has fixed the issue.

**Comment by IzzySoft** [comment]
Looks good currently, thanks!

**Comment by mirfatif** [comment]
@IzzySoft can you please change my email from `mirfatif@gmail.com` to `mirfatif.dev@gmail.com` in F-Droid metadata files of my apps ([PMX](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.mirfatif.permissionmanagerx.yml), [NUH](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.mirfatif.noorulhuda.yml), [MyLocation](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/com.mirfatif.mylocation.yml))?

**Comment by IzzySoft** [comment]
Done, effective with the next sync around 5 pm UTC.

**Comment by mirfatif** [comment]
@IzzySoft I think something went wrong. The files haven't changed.

**Comment by IzzySoft** [comment]
Where did you look? I've changed them for my repo only, if it's that. I'm currently [not active for F-Droid.org](https://gitlab.com/fdroid/admin/-/issues/447), sorry :cry: May I suggest you opening an issue with fdroiddata for changes there?

**Comment by mirfatif** [comment]
Oh sorry. I wasn't aware of that.

**Comment by IzzySoft** [comment]
Hardly anybody is, Irfan. There was no "public communication" about the topic behind that link, sadly – which is one of the reasons I still stay inactive. I had planned to return; but currently I cannot tell if and when that might happen.

**Comment by mirfatif** [comment]
@IzzySoft best wishes.
