### ISSUE TITLE
[Feature Request] implement this for minimized prayer times

### ISSUE THREAD

**Issue by yant0** [mirfatif/NoorUlHuda#3]
the minimized notification is pretty unintuitive for me, ive been using [This](https://github.com/metinkale38/prayer-times-android) for prayer times, hoping you could implement ui somewhat like that :) great app

i want to hear your opinion

**Comment by mirfatif** [comment]
There are technical limitations; theme color, notification size, different form factors etc. And there are personal choices, almost always varying from person to person, more or less.

I'd like to thank @metinkale38 for Prayer Times. It's a more complete and great app. I've been personally using it. NUH only includes its partial functionality, which is essentially required in my view.

> i want to hear your opinion

In my opinion keep using it for a few weeks and you'll get used to 🙂
